name: CppUnit Tests

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ openmpi-bin libopenmpi-dev libcppunit-dev cmake

      - name: Build
        run: |
          cmake -S . -B build
          cmake --build build
          cd build/tests
          ls

      - name: Run tests
        run: |
          ./hello_test

      - name: Run mpi tests
        run: |
          mpirun -np 4 ./mpi_tests
